export const FILMS_TYPES = Object.freeze({
    SET_FILMS: 'SET_FILMS',
    SET_SELECTED_FILM: 'SET_SELECTED_FILM',
    SET_GENRES: 'SET_GENRES',
    SET_FILTERS: 'SET_FILTERS',
    CHANGE_PAGE: 'CHANGE_PAGE',
    SET_SEARCH: 'SET_SEARCH',
    TOGGLE_ERROR: 'TOGGLE_ERROR',
    TOGGLE_LOADING: 'TOGGLE_LOADING',
    RESET_FILTERS: 'RESET_FILTERS'
});

export const FAVOURITES_TYPES = Object.freeze({
    ADD_TO_FAVOURITES: 'ADD_TO_FAVOURITES',
    REMOVE_FROM_FAVOURITES: 'REMOVE_FROM_FAVOURITES'
});

export const FORM_TYPES = Object.freeze({
    CHANGE_SHOW_SIGN_UP_FLAG: 'CHANGE_SHOW_SIGN_UP_FLAG',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    ADD_USER_DATA: 'ADD_USER_DATA'
});

export const NOTIFICATION = Object.freeze({
    SET_NOTIFICATION: 'SET_NOTIFICATION'
});